version: "3"

services:
  app:
    build: ./dating_site # создается образ на основе Dockerfile, путь к Dockerfile
    command: sh -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --no-input
      && sh ./bin/start_gunicorn.sh"
    volumes:
      - ./dating_site:/app/dating_site/
      - static_volume:/app/dating_site/static/
    restart: always


  nginx:
    build: ./nginx
    restart: always
    ports:
      - "5000:80"
    volumes:
      - static_volume:/app/dating_site/static/
    depends_on:
      - app

volumes:
  static_volume:

