# Generated by Django 4.2.2 on 2023-08-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_to_user', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Совпадение',
                'verbose_name_plural': 'Совпадения',
                'db_table': 'dating_site_matches',
            },
        ),
    ]
