# Generated by Django 4.2.2 on 2023-07-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coordinate',
            table='dating_site_coordinate',
        ),
    ]
