# Generated by Django 4.2.2 on 2023-07-17 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list_users', '0002_alter_coordinate_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinate', to=settings.AUTH_USER_MODEL),
        ),
    ]
