# Generated by Django 4.2.2 on 2023-07-05 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_users', '0003_remove_matches_user'),
        ('list_users', '0001_initial'),
        ('register_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coordinate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordinates', to='list_users.coordinate'),
        ),
        migrations.AddField(
            model_name='user',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='likes', to='match_users.matches'),
        ),
    ]
