# Generated by Django 4.2.2 on 2023-07-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
