# Generated by Django 4.2.2 on 2023-08-03 10:03

from django.db import migrations, models
import register_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/default.png', max_length=200, upload_to=register_user.models.get_random_filename, verbose_name='Фото'),
        ),
    ]
