# Generated by Django 4.2.2 on 2023-07-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.TextField(blank=True, choices=[('мужской', 'Мужской'), ('женский', 'Женский')], verbose_name='Пол'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='dating_site_user',
        ),
    ]
