# Generated by Django 4.2.2 on 2023-07-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0002_user_coordinate_user_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='like',
        ),
    ]
