# Generated by Django 4.2.2 on 2023-07-05 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_users', '0002_alter_coordinate_table'),
        ('register_user', '0003_remove_user_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coordinate',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordinates', to='list_users.coordinate'),
        ),
    ]
