# Generated by Django 4.2.2 on 2023-07-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match_users', '0001_initial'),
        ('register_user', '0003_alter_user_sex_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matches',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='match_users.matches'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='images/default.png', max_length=200, upload_to='images/%Y-%m-%d/', verbose_name='Фото'),
        ),
    ]
