# Generated by Django 4.2.2 on 2023-07-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_user', '0004_alter_user_coordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coordinate',
        ),
    ]
