# Generated by Django 4.2.2 on 2023-07-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list_users', '0002_alter_coordinate_table'),
        ('register_user', '0004_alter_user_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='coordinate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinates', to='list_users.coordinate'),
        ),
    ]
